from typing import Dict

# Simple i18n system with a small, extendable dictionary

SUPPORTED_LANGS = ['en', 'de', 'fr', 'nl']

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    # Add common commands first
    'cmd.reviews': {
        'en': 'View shop reviews and ratings',
        'de': 'Shop-Bewertungen ansehen',
        'fr': 'Voir les avis du magasin',
        'nl': 'Winkelbeoordelingen bekijken',
    },

    'en': {
        # Command descriptions
        'cmd.start': 'Open the main menu',
        'cmd.profile': 'View your profile',
        'cmd.cart': 'Open your cart',
        'cmd.orders': 'View your orders',
        'cmd.support': 'Get customer support',
        'cmd.language': 'Change interface language',
        # Support flows
        'support.ticket.created.title': '✅ Support Ticket Created',
        'support.ticket.created.id': '**Ticket ID:** #{id}',
        'support.ticket.created.category': '**Category:** {category}',
        'support.ticket.created.status': '**Status:** Open',
        'support.ticket.created.body': 'Your ticket has been submitted successfully! Our support team will respond within 24 hours.\n\nYou can check your ticket status anytime using /support',

        'support.ticket.cancelled': '❌ Ticket creation cancelled.',

        'support.agent.request.title': '👤 Human Agent Request Received',
        'support.agent.request.body': "Thank you for your request! I've notified our support team that you'd like to speak with a human agent.",
        'support.agent.request.next': '**What happens next:**\n• Our support team will respond to you directly\n• You will receive a personal message from our staff\n• Response time: Usually within 1-2 hours',
        'support.agent.request.meanwhile': '**In the meantime:**\n• You can continue using our bot for other questions\n• Browse our FAQ for quick answers\n• Create a support ticket for detailed issues',
        'support.agent.request.appreciate': 'We appreciate your patience!',

        'support.faq.title': '❓ Frequently Asked Questions',
        'support.faq.q1': '**Q: How do I check my order status?**\nA: Use /orders or click 📦 Orders in main menu.',
        'support.faq.q2': '**Q: What payment methods do you accept?**\nA: We accept Bitcoin (BTC) and Monero (XMR).',
        'support.faq.q3': '**Q: How long does delivery take?**\nA: Delivery times vary by country. Check product details for specifics.',
        'support.faq.q4': '**Q: Can I cancel my order?**\nA: Orders can be cancelled before payment is confirmed.',
        'support.faq.need_more': '**Need more help?** Create a support ticket for personalized assistance!',

        'support.buttons.create': '📝 Create Support Ticket',
        'support.buttons.faq': '❓ Browse FAQ',
        'support.buttons.human': '👤 Speak with Human',
        'support.buttons.menu': '🔙 Main Menu',
        'support.buttons.back_support': '🔙 Back to Support',
        # Support UI
        'support.title': '🆘 Customer Support',
        'support.how_can_help': 'How can we help you today?',
        'support.quick_options': '**Quick Options:**',
        'support.quick_list': '• 📝 Create a support ticket\n• 📋 View your existing tickets\n• ❓ Browse frequently asked questions\n• 💬 Get live assistance',
        'support.auto.head': '**Auto-Response System:**',
        'support.auto.body': 'Our smart system can instantly help with common questions about orders, payments, and products.',
        'support.menu.create': '📝 Create Ticket',
        'support.menu.my': '📋 My Tickets ({count})',
        'support.menu.faq': '❓ FAQ',
        'support.menu.human': '👤 Speak with Human',
        'support.menu.back': '🔙 Back to Support',

        # Auto responses categories
        'support.auto.greeting': "👋 **Hello! Welcome to our support!**\n\nHow can I help you today?\n\n**Quick Help:**\n• 📦 Order issues\n• 💳 Payment problems\n• 🛍️ Product questions\n• 🔧 Technical support\n\nType your question or use /support for more options!",
        'support.auto.order_status': "📦 **Order Status Help**\n\nTo check your order status:\n1. Use /orders command\n2. Or click '📦 Orders' in main menu\n3. Enter your order ID for tracking\n\nNeed more help? Create a support ticket!",
        'support.auto.payment_help': "💳 **Payment Help**\n\nWe accept:\n• Bitcoin (BTC)\n• Monero (XMR)\n\nPayment process:\n1. Add items to cart\n2. Proceed to checkout\n3. Send exact amount to provided wallet\n4. Confirm payment\n\nNeed help? Create a support ticket!",
        'support.auto.product_info': "🛍️ **Product Information**\n\nTo view products:\n1. Click '🛍️ Products' in main menu\n2. Select your country\n3. Browse categories\n4. View product details\n\nNeed specific info? Create a support ticket!",
        'support.auto.shipping': "🚚 **Shipping & Delivery**\n\n**Delivery Times:**\n• EU: 3-7 days\n• USA: 5-10 days\n• Worldwide: 7-14 days\n\n**Shipping Costs:**\n• Varies by country\n• Check delivery options at checkout\n\nNeed specific info? Create a support ticket!",
        'support.auto.refund': "💰 **Refund & Return Policy**\n\n**Refund Policy:**\n• Contact support within 7 days\n• Provide order details\n• Refunds processed within 3-5 business days\n\n**Return Process:**\n• Create support ticket\n• Explain reason for return\n• Follow instructions from support team\n\nNeed help? Create a support ticket!",
        'support.auto.technical': "🔧 **Technical Support**\n\nFor technical issues:\n1. Try restarting your session (🔄 Restart Session)\n2. Clear your cart and try again\n3. If problem persists, create a support ticket\n\nWe'll help you resolve it quickly!",
        'support.auto.general': "❓ **General Help**\n\nQuick help:\n• /start - Main menu\n• /orders - Check orders\n• /notifications - Manage notifications\n• /support - Get help\n\nFor specific questions, create a support ticket!",
        'menu.products': '🛍️ Products',
        'menu.account': '👤 My Account',
        'menu.search': '🔍 Search',
        'menu.cart': '🛒 Cart',
        'menu.orders': '📦 Orders',
        'menu.wishlist': '🎁 Wishlist',
        'menu.support': '🆘 Support',
        'menu.recommendations': '🎯 Recommendations',
        'menu.language': '🌐 Language',
        'menu.pgp': '🔑 PGP Key',
        'menu.updates': '📰 Updates',
        'menu.restart': '🔄 Restart Session',

        'lang.title': 'Select Language / Sprache wählen / Choisir la langue / Taal selecteren',
        'lang.updated': '✅ Language updated',
        'lang.back': '🔙 Back to main menu',
        'lang.english': 'English',
        'lang.german': 'Deutsch',
        'lang.french': 'Français',
        'lang.dutch': 'Nederlands',

        # Phrase setup
        'phrase.title': '🔐 Set Your Secret Phrase Code',
        'phrase.welcome': 'Welcome to {shop}!',
        'phrase.instructions': 'To access our shop, please set your own secret phrase code.',
        'phrase.requirements': 'Requirements:',
        'phrase.requirements.lines': '• 20-40 characters long\n• Can include letters, numbers, and symbols\n• Make it unique and memorable',
        'phrase.example': 'Example: `{example}`',
        'phrase.send': 'Just type your secret phrase code and send it to this chat.',
        'phrase.too_short': '❌ Secret Phrase Too Short',
        'phrase.too_long': '❌ Secret Phrase Too Long',
        'phrase.length.current': 'Current length: {length} characters',
        'phrase.length.required': 'Required: 20-40 characters',

        # Cart
        'cart.title': '🛒 Your Cart',
        'cart.total_items': 'Total: €{total}\nItems: {items}',
        'cart.empty': 'Your cart is empty. Start shopping to add items!',
        'cart.button.view': '🛒 View Cart',
        'cart.button.browse': '🛍️ Browse Products',
        'cart.button.back': '🔙 Back to Menu',

        # Checkout & invoice
        'checkout.invoice.title': '🏪 {shop}',
        'checkout.invoice.secret': 'Your secret phrase: {secret}',
        'checkout.invoice.id': 'Invoice #{id}',
        'checkout.invoice.status': 'Status: 🕒 Pending Checkout',
        'checkout.invoice.instructions': 'Enter discount code, payment method, address and delivery method. Once completed you will receive payment details.',
        'checkout.invoice.total': '**Total: €{total}**',
        'checkout.invoice.subtotal': '**Subtotal: €{subtotal}**',
        'checkout.invoice.discount': '**Discount ({code}): -€{amount}**',
        'checkout.buttons.discount': 'Enter a discount code',
        'checkout.buttons.select_payment': 'Select Payment Method',
        'checkout.buttons.enter_address': 'Enter Delivery Address',
        'checkout.buttons.select_delivery': 'Select Delivery Method',
        'checkout.buttons.tracking': '📦 Tracking Information',
        'checkout.buttons.delete': 'Delete Order',
        'checkout.buttons.back': 'Back',

        # Delivery
        'delivery.select.title': '💳 Payment Method Selection',
        'delivery.select.summary': '**Cart Total: €{cart}**\n**Delivery: €{delivery}**\n**Total: €{total}**',
        'delivery.select.label': 'Select your payment method:',
        'payment.method.btc': '₿ Bitcoin (BTC)',
        'payment.method.xmr': '🔒 Monero (XMR)',

        # Address
        'address.title': '🏠 Delivery Address Required',
        'address.secret': 'Your secret phrase: {secret}',
        'address.instructions': 'Please type your address in this format:',
        'address.example.lines': '(YOUR NAME) - John Smith\n(STREET NAME + NUMBER) - Main St 123\n(CITY) - Berlin\n(POSTAL CODE) - 10115\n(COUNTRY) - GERMANY',
        'address.just_type': 'Just type your address in the format above and send it to this chat.',

        # Payment details
        'payment.title': 'Payment for Order #{order}',
        'payment.method': '**Payment method:** {method}',
        'payment.transfer_exact': '**Transfer EXACT amount:** {amount}',
        'payment.to_address': '**To next address:** {address}',
        'payment.warning': '**Please send EXACT amount shown above carefully!**',
        'payment.buttons.cancel': '❌ Cancel',
        'payment.buttons.paid': '✅ I paid (starts the checking)',

        # Order summary
        'order.summary.title': '**Your order:**',
        'order.summary.cart': '🛒 Your cart:',
        'order.summary.delivery': '🚚 Your delivery method:',
        'order.summary.payment': '💳 Your payment method:',
        'order.summary.address': '📝 Your order note:',
        'order.summary.correct': '**Is this correct?**',
        'order.summary.no': '❌ No! Create order again',
        'order.summary.yes': '✅ Yes! Order is correct',
    },
    'de': {
        'cmd.start': 'Hauptmenü öffnen',
        'cmd.profile': 'Dein Profil anzeigen',
        'cmd.cart': 'Warenkorb öffnen',
        'cmd.orders': 'Bestellungen anzeigen',
        'cmd.support': 'Kundensupport erhalten',
        'cmd.language': 'Sprache ändern',
        'support.ticket.created.title': '✅ Support-Ticket erstellt',
        'support.ticket.created.id': '**Ticket-ID:** #{id}',
        'support.ticket.created.category': '**Kategorie:** {category}',
        'support.ticket.created.status': '**Status:** Offen',
        'support.ticket.created.body': 'Dein Ticket wurde erfolgreich eingereicht! Unser Team antwortet innerhalb von 24 Stunden.\n\nDu kannst den Status jederzeit mit /support prüfen.',

        'support.ticket.cancelled': '❌ Ticket-Erstellung abgebrochen.',

        'support.agent.request.title': '👤 Anfrage nach menschlichem Support erhalten',
        'support.agent.request.body': 'Danke! Wir haben das Support-Team informiert, dass du mit einem Menschen sprechen möchtest.',
        'support.agent.request.next': '**Wie geht es weiter:**\n• Unser Team antwortet dir direkt\n• Du erhältst eine persönliche Nachricht\n• Antwortzeit: In der Regel 1–2 Stunden',
        'support.agent.request.meanwhile': '**In der Zwischenzeit:**\n• Du kannst den Bot weiter nutzen\n• Stöbere in der FAQ\n• Erstelle ein ausführliches Ticket',
        'support.agent.request.appreciate': 'Danke für deine Geduld!',

        'support.faq.title': '❓ Häufige Fragen (FAQ)',
        'support.faq.q1': '**F: Wie prüfe ich meinen Bestellstatus?**\nA: Nutze /orders oder 📦 Bestellungen im Menü.',
        'support.faq.q2': '**F: Welche Zahlungsmethoden?**\nA: Bitcoin (BTC) und Monero (XMR).',
        'support.faq.q3': '**F: Wie lange dauert die Lieferung?**\nA: Abhängig vom Land. Siehe Produktdetails.',
        'support.faq.q4': '**F: Kann ich stornieren?**\nA: Vor Zahlungsbestätigung ist eine Stornierung möglich.',
        'support.faq.need_more': '**Mehr Hilfe benötigt?** Erstelle ein Ticket für persönliche Unterstützung!',

        'support.buttons.create': '📝 Support-Ticket erstellen',
        'support.buttons.faq': '❓ FAQ ansehen',
        'support.buttons.human': '👤 Mit Mensch sprechen',
        'support.buttons.menu': '🔙 Hauptmenü',
        'support.buttons.back_support': '🔙 Zurück zum Support',
        'support.title': '🆘 Kundensupport',
        'support.how_can_help': 'Wie können wir heute helfen?',
        'support.quick_options': '**Schnelloptionen:**',
        'support.quick_list': '• 📝 Support-Ticket erstellen\n• 📋 Meine Tickets ansehen\n• ❓ FAQ durchsuchen\n• 💬 Live-Unterstützung',
        'support.auto.head': '**Auto-Response System:**',
        'support.auto.body': 'Unser System hilft sofort bei häufigen Fragen zu Bestellungen, Zahlungen und Produkten.',
        'support.menu.create': '📝 Ticket erstellen',
        'support.menu.my': '📋 Meine Tickets ({count})',
        'support.menu.faq': '❓ FAQ',
        'support.menu.human': '👤 Mit Mensch sprechen',
        'support.menu.back': '🔙 Zurück zum Support',

        'support.auto.greeting': "👋 **Hallo! Willkommen beim Support!**\n\nWie können wir helfen?\n\n**Schnellhilfe:**\n• 📦 Bestellprobleme\n• 💳 Zahlungsprobleme\n• 🛍️ Produktfragen\n• 🔧 Technischer Support\n\nSchreibe deine Frage oder nutze /support!",
        'support.auto.order_status': "📦 **Hilfe zum Bestellstatus**\n\nStatus prüfen:\n1. /orders verwenden\n2. Oder '📦 Bestellungen' im Hauptmenü\n3. Bestell-ID eingeben\n\nMehr Hilfe? Ticket erstellen!",
        'support.auto.payment_help': "💳 **Zahlungshilfe**\n\nWir akzeptieren:\n• Bitcoin (BTC)\n• Monero (XMR)\n\nZahlung:\n1. In den Warenkorb legen\n2. Zur Kasse gehen\n3. Exakten Betrag an Wallet senden\n4. Zahlung bestätigen\n\nMehr Hilfe? Ticket erstellen!",
        'support.auto.product_info': "🛍️ **Produktinformationen**\n\nProdukte ansehen:\n1. '🛍️ Produkte' im Hauptmenü\n2. Land wählen\n3. Kategorien durchsuchen\n4. Details ansehen\n\nSpezifische Infos? Ticket erstellen!",
        'support.auto.shipping': "🚚 **Versand & Lieferung**\n\n**Lieferzeiten:**\n• EU: 3–7 Tage\n• USA: 5–10 Tage\n• Weltweit: 7–14 Tage\n\n**Versandkosten:**\n• Je nach Land\n• Auswahl an der Kasse\n\nSpezifische Infos? Ticket erstellen!",
        'support.auto.refund': "💰 **Rückerstattung & Rückgabe**\n\n**Rückerstattung:**\n• Innerhalb von 7 Tagen melden\n• Bestelldaten angeben\n• Rückerstattung in 3–5 Werktagen\n\n**Rückgabe:**\n• Ticket erstellen\n• Grund erklären\n• Anweisungen folgen\n\nMehr Hilfe? Ticket erstellen!",
        'support.auto.technical': "🔧 **Technischer Support**\n\nBei Problemen:\n1. Sitzung neu starten (🔄)\n2. Warenkorb leeren und erneut versuchen\n3. Wenn weiter besteht: Ticket erstellen\n\nWir helfen schnell!",
        'support.auto.general': "❓ **Allgemeine Hilfe**\n\nSchnellhilfe:\n• /start - Hauptmenü\n• /orders - Bestellungen\n• /notifications - Benachrichtigungen\n• /support - Hilfe\n\nFür Details: Ticket erstellen!",
        'menu.products': '🛍️ Produkte',
        'menu.account': '👤 Mein Konto',
        'menu.search': '🔍 Suche',
        'menu.cart': '🛒 Warenkorb',
        'menu.orders': '📦 Bestellungen',
        'menu.wishlist': '🎁 Wunschliste',
        'menu.support': '🆘 Support',
        'menu.recommendations': '🎯 Empfehlungen',
        'menu.language': '🌐 Sprache',
        'menu.pgp': '🔑 PGP-Schlüssel',
        'menu.updates': '📰 Neuigkeiten',
        'menu.restart': '🔄 Sitzung neu starten',

        'lang.title': 'Sprache wählen / Select Language / Choisir la langue / Taal selecteren',
        'lang.updated': '✅ Sprache aktualisiert',
        'lang.back': '🔙 Zurück zum Hauptmenü',
        'lang.english': 'English',
        'lang.german': 'Deutsch',
        'lang.french': 'Français',
        'lang.dutch': 'Nederlands',

        'phrase.title': '🔐 Geheimen Code festlegen',
        'phrase.welcome': 'Willkommen bei {shop}!',
        'phrase.instructions': 'Bitte lege deinen eigenen geheimen Zugangscode fest.',
        'phrase.requirements': 'Anforderungen:',
        'phrase.requirements.lines': '• 20–40 Zeichen\n• Buchstaben, Zahlen und Symbole erlaubt\n• Einzigartig und merkbar',
        'phrase.example': 'Beispiel: `{example}`',
        'phrase.send': 'Schreibe deinen Code hier und sende ihn.',
        'phrase.too_short': '❌ Geheimer Code zu kurz',
        'phrase.too_long': '❌ Geheimer Code zu lang',
        'phrase.length.current': 'Aktuelle Länge: {length} Zeichen',
        'phrase.length.required': 'Erforderlich: 20–40 Zeichen',

        'cart.title': '🛒 Dein Warenkorb',
        'cart.total_items': 'Summe: €{total}\nArtikel: {items}',
        'cart.empty': 'Dein Warenkorb ist leer. Lege los mit dem Einkaufen!',
        'cart.button.view': '🛒 Warenkorb ansehen',
        'cart.button.browse': '🛍️ Produkte ansehen',
        'cart.button.back': '🔙 Zurück zum Menü',

        'checkout.invoice.title': '🏪 {shop}',
        'checkout.invoice.secret': 'Dein geheimer Code: {secret}',
        'checkout.invoice.id': 'Rechnung #{id}',
        'checkout.invoice.status': 'Status: 🕒 Kasse ausstehend',
        'checkout.invoice.instructions': 'Gutscheincode, Zahlungsmethode, Adresse und Versand auswählen. Danach erhältst du Zahlungsdetails.',
        'checkout.invoice.total': '**Gesamt: €{total}**',
        'checkout.invoice.subtotal': '**Zwischensumme: €{subtotal}**',
        'checkout.invoice.discount': '**Rabatt ({code}): -€{amount}**',
        'checkout.buttons.discount': 'Gutscheincode eingeben',
        'checkout.buttons.select_payment': 'Zahlungsmethode wählen',
        'checkout.buttons.enter_address': 'Lieferadresse eingeben',
        'checkout.buttons.select_delivery': 'Versandart wählen',
        'checkout.buttons.tracking': '📦 Sendungsverfolgung',
        'checkout.buttons.delete': 'Bestellung löschen',
        'checkout.buttons.back': 'Zurück',

        'delivery.select.title': '💳 Zahlungsauswahl',
        'delivery.select.summary': '**Warenkorb: €{cart}**\n**Versand: €{delivery}**\n**Gesamt: €{total}**',
        'delivery.select.label': 'Bitte Zahlungsmethode wählen:',
        'payment.method.btc': '₿ Bitcoin (BTC)',
        'payment.method.xmr': '🔒 Monero (XMR)',

        'address.title': '🏠 Lieferadresse erforderlich',
        'address.secret': 'Dein geheimer Code: {secret}',
        'address.instructions': 'Bitte gib deine Adresse in diesem Format ein:',
        'address.example.lines': '(NAME) - Max Mustermann\n(STRASSE + NR.) - Hauptstr. 1\n(STADT) - Berlin\n(PLZ) - 10115\n(LAND) - DEUTSCHLAND',
        'address.just_type': 'Schreibe die Adresse im obigen Format und sende sie hierher.',

        'payment.title': 'Zahlung für Bestellung #{order}',
        'payment.method': '**Zahlungsmethode:** {method}',
        'payment.transfer_exact': '**EXAKTEN Betrag überweisen:** {amount}',
        'payment.to_address': '**An folgende Adresse:** {address}',
        'payment.warning': '**Bitte den exakten Betrag sorgfältig senden!**',
        'payment.buttons.cancel': '❌ Abbrechen',
        'payment.buttons.paid': '✅ Ich habe bezahlt (Prüfung starten)',

        'order.summary.title': '**Deine Bestellung:**',
        'order.summary.cart': '🛒 Dein Warenkorb:',
        'order.summary.delivery': '🚚 Deine Versandart:',
        'order.summary.payment': '💳 Deine Zahlungsmethode:',
        'order.summary.address': '📝 Deine Bestellnotiz:',
        'order.summary.correct': '**Stimmt das?**',
        'order.summary.no': '❌ Nein! Bestellung neu erstellen',
        'order.summary.yes': '✅ Ja! Bestellung ist korrekt',
    },
    'fr': {
        'cmd.start': 'Ouvrir le menu principal',
        'cmd.profile': 'Voir votre profil',
        'cmd.cart': 'Ouvrir votre panier',
        'cmd.orders': 'Voir vos commandes',
        'cmd.support': 'Obtenir de l’assistance',
        'cmd.language': 'Changer la langue',
        'support.ticket.created.title': '✅ Ticket de support créé',
        'support.ticket.created.id': '**ID du ticket :** #{id}',
        'support.ticket.created.category': '**Catégorie :** {category}',
        'support.ticket.created.status': '**Statut :** Ouvert',
        'support.ticket.created.body': 'Votre ticket a été soumis avec succès ! Notre équipe répond sous 24h.\n\nVous pouvez consulter le statut via /support.',

        'support.ticket.cancelled': '❌ Création du ticket annulée.',

        'support.agent.request.title': '👤 Demande d’agent humain reçue',
        'support.agent.request.body': "Merci ! Nous avons informé l’équipe de votre demande d’échanger avec un humain.",
        'support.agent.request.next': '**Prochaine étape :**\n• Notre équipe vous répond directement\n• Vous recevrez un message personnel\n• Délai : 1–2 heures',
        'support.agent.request.meanwhile': '**En attendant :**\n• Continuez à utiliser le bot\n• Parcourez la FAQ\n• Créez un ticket détaillé',
        'support.agent.request.appreciate': 'Merci pour votre patience !',

        'support.faq.title': '❓ Foire aux questions (FAQ)',
        'support.faq.q1': '**Q : Comment vérifier le statut de ma commande ?**\nR : Utilisez /orders ou 📦 Commandes.',
        'support.faq.q2': '**Q : Quels moyens de paiement acceptez-vous ?**\nR : Bitcoin (BTC) et Monero (XMR).',
        'support.faq.q3': '**Q : Délais de livraison ?**\nR : Varient selon le pays. Voir la fiche produit.',
        'support.faq.q4': '**Q : Puis-je annuler ?**\nR : Oui, avant la confirmation du paiement.',
        'support.faq.need_more': '**Besoin d’aide ?** Créez un ticket pour une assistance personnalisée !',

        'support.buttons.create': '📝 Créer un ticket',
        'support.buttons.faq': '❓ Parcourir la FAQ',
        'support.buttons.human': '👤 Parler à un humain',
        'support.buttons.menu': '🔙 Menu principal',
        'support.buttons.back_support': '🔙 Retour au support',
        'support.title': '🆘 Support client',
        'support.how_can_help': 'Comment pouvons-nous vous aider aujourd’hui ?',
        'support.quick_options': '**Options rapides :**',
        'support.quick_list': '• 📝 Créer un ticket\n• 📋 Voir mes tickets\n• ❓ Parcourir la FAQ\n• 💬 Assistance en direct',
        'support.auto.head': '**Réponses automatiques :**',
        'support.auto.body': 'Notre système aide instantanément pour les questions fréquentes (commandes, paiements, produits).',
        'support.menu.create': '📝 Créer un ticket',
        'support.menu.my': '📋 Mes tickets ({count})',
        'support.menu.faq': '❓ FAQ',
        'support.menu.human': '👤 Parler à un humain',
        'support.menu.back': '🔙 Retour au support',

        'support.auto.greeting': "👋 **Bonjour ! Bienvenue au support !**\n\nComment puis-je vous aider ?\n\n**Aide rapide :**\n• 📦 Problèmes de commande\n• 💳 Problèmes de paiement\n• 🛍️ Questions produits\n• 🔧 Support technique\n\nTapez votre question ou utilisez /support !",
        'support.auto.order_status': "📦 **Statut de commande**\n\nPour vérifier :\n1. Utilisez /orders\n2. Ou '📦 Commandes' dans le menu\n3. Entrez l’ID\n\nBesoin d’aide ? Créez un ticket !",
        'support.auto.payment_help': "💳 **Aide au paiement**\n\nNous acceptons :\n• Bitcoin (BTC)\n• Monero (XMR)\n\nPaiement :\n1. Ajouter au panier\n2. Passer à la caisse\n3. Envoyer le montant exact\n4. Confirmer\n\nBesoin d’aide ? Créez un ticket !",
        'support.auto.product_info': "🛍️ **Informations produit**\n\nVoir les produits :\n1. '🛍️ Produits' dans le menu\n2. Choisir le pays\n3. Parcourir les catégories\n4. Voir les détails\n\nBesoin d’infos ? Créez un ticket !",
        'support.auto.shipping': "🚚 **Expédition & Livraison**\n\n**Délais :**\n• UE : 3–7 jours\n• USA : 5–10 jours\n• Monde : 7–14 jours\n\n**Frais :**\n• Varient selon le pays\n• Options à la caisse\n\nBesoin d’infos ? Créez un ticket !",
        'support.auto.refund': "💰 **Remboursement & Retour**\n\n**Remboursement :**\n• Contacter le support sous 7 jours\n• Donner les détails\n• 3–5 jours ouvrés\n\n**Retour :**\n• Créer un ticket\n• Expliquer le motif\n• Suivre les instructions\n\nBesoin d’aide ? Créez un ticket !",
        'support.auto.technical': "🔧 **Support technique**\n\nEn cas de problème :\n1. Redémarrer la session (🔄)\n2. Vider le panier et réessayer\n3. Si persiste : créer un ticket\n\nNous vous aidons rapidement !",
        'support.auto.general': "❓ **Aide générale**\n\nAide rapide :\n• /start - Menu principal\n• /orders - Commandes\n• /notifications - Notifications\n• /support - Support\n\nPour des questions précises, créez un ticket !",
        'menu.products': '🛍️ Produits',
        'menu.account': '👤 Mon Compte',
        'menu.search': '🔍 Recherche',
        'menu.cart': '🛒 Panier',
        'menu.orders': '📦 Commandes',
        'menu.wishlist': '🎁 Liste de souhaits',
        'menu.support': '🆘 Support',
        'menu.recommendations': '🎯 Recommandations',
        'menu.language': '🌐 Langue',
        'menu.pgp': '🔑 Clé PGP',
        'menu.updates': '📰 Mises à jour',
        'menu.restart': '🔄 Redémarrer la session',

        'lang.title': 'Choisir la langue / Select Language / Sprache wählen / Taal selecteren',
        'lang.updated': '✅ Langue mise à jour',
        'lang.back': '🔙 Retour au menu principal',
        'lang.english': 'English',
        'lang.german': 'Deutsch',
        'lang.french': 'Français',
        'lang.dutch': 'Nederlands',

        'phrase.title': '🔐 Définir votre code secret',
        'phrase.welcome': 'Bienvenue chez {shop} !',
        'phrase.instructions': "Pour accéder à la boutique, définissez votre propre code d’accès.",
        'phrase.requirements': 'Exigences :',
        'phrase.requirements.lines': '• 20-40 caractères\n• Lettres, chiffres et symboles\n• Unique et mémorisable',
        'phrase.example': 'Exemple : `{example}`',
        'phrase.send': 'Saisissez votre code secret et envoyez-le ici.',
        'phrase.too_short': '❌ Code secret trop court',
        'phrase.too_long': '❌ Code secret trop long',
        'phrase.length.current': 'Longueur actuelle : {length} caractères',
        'phrase.length.required': 'Requis : 20-40 caractères',

        'cart.title': '🛒 Votre panier',
        'cart.total_items': 'Total : €{total}\nArticles : {items}',
        'cart.empty': 'Votre panier est vide. Commencez vos achats !',
        'cart.button.view': '🛒 Voir le panier',
        'cart.button.browse': '🛍️ Parcourir les produits',
        'cart.button.back': '🔙 Retour au menu',

        'checkout.invoice.title': '🏪 {shop}',
        'checkout.invoice.secret': 'Votre code secret : {secret}',
        'checkout.invoice.id': 'Facture #{id}',
        'checkout.invoice.status': 'Statut : 🕒 Caisse en attente',
        'checkout.invoice.instructions': 'Entrez le code promo, la méthode de paiement, l’adresse et la livraison. Vous recevrez ensuite les détails de paiement.',
        'checkout.invoice.total': '**Total : €{total}**',
        'checkout.invoice.subtotal': '**Sous-total : €{subtotal}**',
        'checkout.invoice.discount': '**Remise ({code}) : -€{amount}**',
        'checkout.buttons.discount': 'Entrer un code promo',
        'checkout.buttons.select_payment': 'Choisir le mode de paiement',
        'checkout.buttons.enter_address': 'Saisir l’adresse de livraison',
        'checkout.buttons.select_delivery': 'Choisir le mode de livraison',
        'checkout.buttons.tracking': '📦 Suivi de commande',
        'checkout.buttons.delete': 'Supprimer la commande',
        'checkout.buttons.back': 'Retour',

        'delivery.select.title': '💳 Sélection du paiement',
        'delivery.select.summary': '**Panier : €{cart}**\n**Livraison : €{delivery}**\n**Total : €{total}**',
        'delivery.select.label': 'Sélectionnez votre mode de paiement :',
        'payment.method.btc': '₿ Bitcoin (BTC)',
        'payment.method.xmr': '🔒 Monero (XMR)',

        'address.title': '🏠 Adresse de livraison requise',
        'address.secret': 'Votre code secret : {secret}',
        'address.instructions': 'Veuillez saisir votre adresse au format suivant :',
        'address.example.lines': '(NOM) - Jean Dupont\n(RUE + NUMÉRO) - Rue Principale 123\n(VILLE) - Paris\n(CODE POSTAL) - 75001\n(PAYS) - FRANCE',
        'address.just_type': 'Tapez simplement votre adresse et envoyez-la ici.',

        'payment.title': 'Paiement pour la commande #{order}',
        'payment.method': '**Mode de paiement :** {method}',
        'payment.transfer_exact': '**Transférez le montant EXACT :** {amount}',
        'payment.to_address': '**À l’adresse suivante :** {address}',
        'payment.warning': '**Veuillez envoyer exactement le montant indiqué !**',
        'payment.buttons.cancel': '❌ Annuler',
        'payment.buttons.paid': '✅ J’ai payé (démarrer la vérification)',

        'order.summary.title': '**Votre commande :**',
        'order.summary.cart': '🛒 Votre panier :',
        'order.summary.delivery': '🚚 Votre mode de livraison :',
        'order.summary.payment': '💳 Votre mode de paiement :',
        'order.summary.address': '📝 Votre note de commande :',
        'order.summary.correct': '**Est-ce correct ?**',
        'order.summary.no': '❌ Non ! Refaire la commande',
        'order.summary.yes': '✅ Oui ! La commande est correcte',
    },
    'nl': {
        'cmd.start': 'Hoofdmenu openen',
        'cmd.profile': 'Je profiel bekijken',
        'cmd.cart': 'Winkelwagen openen',
        'cmd.orders': 'Bestellingen bekijken',
        'cmd.support': 'Klantenservice openen',
        'cmd.language': 'Taal wijzigen',
        'support.ticket.created.title': '✅ Supportticket aangemaakt',
        'support.ticket.created.id': '**Ticket-ID:** #{id}',
        'support.ticket.created.category': '**Categorie:** {category}',
        'support.ticket.created.status': '**Status:** Open',
        'support.ticket.created.body': 'Je ticket is aangemaakt! Ons team reageert binnen 24 uur.\n\nJe kunt de status bekijken met /support.',

        'support.ticket.cancelled': '❌ Ticket aanmaken geannuleerd.',

        'support.agent.request.title': '👤 Verzoek om medewerker ontvangen',
        'support.agent.request.body': 'Bedankt! We hebben het team geïnformeerd dat je met een medewerker wilt praten.',
        'support.agent.request.next': '**Wat gebeurt er nu:**\n• Het team reageert direct\n• Je ontvangt een persoonlijk bericht\n• Reactietijd: meestal 1–2 uur',
        'support.agent.request.meanwhile': '**Ondertussen:**\n• Blijf de bot gebruiken\n• Bekijk de FAQ\n• Maak een gedetailleerd ticket',
        'support.agent.request.appreciate': 'Bedankt voor je geduld!',

        'support.faq.title': '❓ Veelgestelde vragen (FAQ)',
        'support.faq.q1': '**V: Hoe check ik mijn bestelstatus?**\nA: Gebruik /orders of 📦 Bestellingen.',
        'support.faq.q2': '**V: Welke betaalmethoden?**\nA: Bitcoin (BTC) en Monero (XMR).',
        'support.faq.q3': '**V: Hoelang duurt levering?**\nA: Afhankelijk van land. Zie productdetails.',
        'support.faq.q4': '**V: Kan ik annuleren?**\nA: Ja, vóór bevestiging van betaling.',
        'support.faq.need_more': '**Meer hulp nodig?** Maak een ticket aan voor persoonlijke hulp!',

        'support.buttons.create': '📝 Supportticket aanmaken',
        'support.buttons.faq': '❓ FAQ bekijken',
        'support.buttons.human': '👤 Met medewerker praten',
        'support.buttons.menu': '🔙 Hoofdmenu',
        'support.buttons.back_support': '🔙 Terug naar support',
        'support.title': '🆘 Klantenservice',
        'support.how_can_help': 'Waarmee kunnen we je vandaag helpen?',
        'support.quick_options': '**Snelkeuzes:**',
        'support.quick_list': '• 📝 Ticket aanmaken\n• 📋 Mijn tickets bekijken\n• ❓ FAQ\n• 💬 Live hulp',
        'support.auto.head': '**Automatische antwoorden:**',
        'support.auto.body': 'Ons slimme systeem helpt direct met veelgestelde vragen over bestellingen, betalingen en producten.',
        'support.menu.create': '📝 Ticket aanmaken',
        'support.menu.my': '📋 Mijn tickets ({count})',
        'support.menu.faq': '❓ FAQ',
        'support.menu.human': '👤 Met een medewerker praten',
        'support.menu.back': '🔙 Terug naar support',

        'support.auto.greeting': "👋 **Hallo! Welkom bij de support!**\n\nWaarmee kan ik helpen?\n\n**Snelhulp:**\n• 📦 Bestelproblemen\n• 💳 Betaalproblemen\n• 🛍️ Productvragen\n• 🔧 Technische hulp\n\nTyp je vraag of gebruik /support!",
        'support.auto.order_status': "📦 **Bestelstatus**\n\nControleren:\n1. Gebruik /orders\n2. Of '📦 Bestellingen' in het menu\n3. Vul bestel-ID in\n\nMeer hulp? Maak een ticket!",
        'support.auto.payment_help': "💳 **Betalingshulp**\n\nWij accepteren:\n• Bitcoin (BTC)\n• Monero (XMR)\n\nBetaling:\n1. Voeg toe aan winkelwagen\n2. Naar afrekenen\n3. Exact bedrag overmaken\n4. Bevestigen\n\nMeer hulp? Ticket aanmaken!",
        'support.auto.product_info': "🛍️ **Productinformatie**\n\nProducten bekijken:\n1. '🛍️ Producten' in menu\n2. Land kiezen\n3. Categorieën bekijken\n4. Details bekijken\n\nSpecifieke info? Ticket aanmaken!",
        'support.auto.shipping': "🚚 **Verzending & Levering**\n\n**Levertijden:**\n• EU: 3–7 dagen\n• USA: 5–10 dagen\n• Wereld: 7–14 dagen\n\n**Kosten:**\n• Afhankelijk van land\n• Opties bij afrekenen\n\nSpecifieke info? Ticket aanmaken!",
        'support.auto.refund': "💰 **Restitutie & Retour**\n\n**Restitutie:**\n• Binnen 7 dagen melden\n• Bestelgegevens geven\n• 3–5 werkdagen\n\n**Retour:**\n• Ticket aanmaken\n• Reden toelichten\n• Instructies volgen\n\nMeer hulp? Ticket aanmaken!",
        'support.auto.technical': "🔧 **Technische hulp**\n\nBij problemen:\n1. Sessie herstarten (🔄)\n2. Winkelwagen legen en opnieuw proberen\n3. Blijft het? Ticket aanmaken\n\nWe helpen snel!",
        'support.auto.general': "❓ **Algemene hulp**\n\nSnelhulp:\n• /start - Hoofdmenu\n• /orders - Bestellingen\n• /notifications - Meldingen\n• /support - Support\n\nVoor specifieke vragen: ticket aanmaken!",
        'menu.products': '🛍️ Producten',
        'menu.account': '👤 Mijn account',
        'menu.search': '🔍 Zoeken',
        'menu.cart': '🛒 Winkelwagen',
        'menu.orders': '📦 Bestellingen',
        'menu.wishlist': '🎁 Verlanglijst',
        'menu.support': '🆘 Support',
        'menu.recommendations': '🎯 Aanbevelingen',
        'menu.language': '🌐 Taal',
        'menu.pgp': '🔑 PGP-sleutel',
        'menu.updates': '📰 Updates',
        'menu.restart': '🔄 Sessie herstarten',

        'lang.title': 'Taal selecteren / Select Language / Sprache wählen / Choisir la langue',
        'lang.updated': '✅ Taal bijgewerkt',
        'lang.back': '🔙 Terug naar hoofdmenu',
        'lang.english': 'English',
        'lang.german': 'Deutsch',
        'lang.french': 'Français',
        'lang.dutch': 'Nederlands',

        'phrase.title': '🔐 Stel je geheime code in',
        'phrase.welcome': 'Welkom bij {shop}!',
        'phrase.instructions': 'Stel je eigen geheime toegangscode in om de shop te gebruiken.',
        'phrase.requirements': 'Vereisten:',
        'phrase.requirements.lines': '• 20-40 tekens\n• Letters, cijfers en symbolen\n• Uniek en onthoudbaar',
        'phrase.example': 'Voorbeeld: `{example}`',
        'phrase.send': 'Typ je geheime code en stuur die hier.',
        'phrase.too_short': '❌ Geheime code te kort',
        'phrase.too_long': '❌ Geheime code te lang',
        'phrase.length.current': 'Huidige lengte: {length} tekens',
        'phrase.length.required': 'Vereist: 20-40 tekens',

        'cart.title': '🛒 Je winkelwagen',
        'cart.total_items': 'Totaal: €{total}\nItems: {items}',
        'cart.empty': 'Je winkelwagen is leeg. Begin met shoppen!',
        'cart.button.view': '🛒 Winkelwagen bekijken',
        'cart.button.browse': '🛍️ Producten bekijken',
        'cart.button.back': '🔙 Terug naar menu',

        'checkout.invoice.title': '🏪 {shop}',
        'checkout.invoice.secret': 'Je geheime code: {secret}',
        'checkout.invoice.id': 'Factuur #{id}',
        'checkout.invoice.status': 'Status: 🕒 Afrekenen in behandeling',
        'checkout.invoice.instructions': 'Voer kortingscode, betalingsmethode, adres en levering in. Daarna ontvang je betalingsdetails.',
        'checkout.invoice.total': '**Totaal: €{total}**',
        'checkout.invoice.subtotal': '**Subtotaal: €{subtotal}**',
        'checkout.invoice.discount': '**Korting ({code}): -€{amount}**',
        'checkout.buttons.discount': 'Kortingscode invoeren',
        'checkout.buttons.select_payment': 'Betalingsmethode kiezen',
        'checkout.buttons.enter_address': 'Bezorgadres invoeren',
        'checkout.buttons.select_delivery': 'Leveringsmethode kiezen',
        'checkout.buttons.tracking': '📦 Track & Trace',
        'checkout.buttons.delete': 'Bestelling verwijderen',
        'checkout.buttons.back': 'Terug',

        'delivery.select.title': '💳 Betalingskeuze',
        'delivery.select.summary': '**Winkelwagen: €{cart}**\n**Levering: €{delivery}**\n**Totaal: €{total}**',
        'delivery.select.label': 'Kies je betalingsmethode:',
        'payment.method.btc': '₿ Bitcoin (BTC)',
        'payment.method.xmr': '🔒 Monero (XMR)',

        'address.title': '🏠 Bezorgadres vereist',
        'address.secret': 'Je geheime code: {secret}',
        'address.instructions': 'Voer je adres in volgens dit format:',
        'address.example.lines': '(NAAM) - Jan Jansen\n(STRAAT + NUMMER) - Hoofdstraat 123\n(STAD) - Amsterdam\n(POSTCODE) - 1011 AA\n(LAND) - NEDERLAND',
        'address.just_type': 'Typ je adres in bovenstaand format en stuur het hier.',

        'payment.title': 'Betaling voor bestelling #{order}',
        'payment.method': '**Betalingsmethode:** {method}',
        'payment.transfer_exact': '**Maak EXACT dit bedrag over:** {amount}',
        'payment.to_address': '**Naar dit adres:** {address}',
        'payment.warning': '**Stuur exact het bovenstaande bedrag!**',
        'payment.buttons.cancel': '❌ Annuleren',
        'payment.buttons.paid': '✅ Ik heb betaald (controle starten)',

        'order.summary.title': '**Je bestelling:**',
        'order.summary.cart': '🛒 Je winkelwagen:',
        'order.summary.delivery': '🚚 Je leveringsmethode:',
        'order.summary.payment': '💳 Je betalingsmethode:',
        'order.summary.address': '📝 Je bestelnotitie:',
        'order.summary.correct': '**Klopt dit?**',
        'order.summary.no': '❌ Nee! Opnieuw maken',
        'order.summary.yes': '✅ Ja! Klopt',
    },
}

def normalize_lang(lang: str) -> str:
    if not lang:
        return 'en'
    lang = lang.lower()
    return lang if lang in SUPPORTED_LANGS else 'en'

def t(lang: str, key: str, default: str = None) -> str:
    l = normalize_lang(lang)
    return TRANSLATIONS.get(l, {}).get(key, default if default is not None else TRANSLATIONS['en'].get(key, key))

def tf(lang: str, key: str, **kwargs) -> str:
    return t(lang, key).format(**kwargs)


